apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: prod-topic
  labels:
    strimzi.io/cluster: kafka-test
spec:
  partitions: 20
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824