# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
endpoints:
  enabled: false
  health:
    enabled: true

# Camel Spring Boot
camel:
  springboot:
    name: camel-kafka-tls
  component:
    kafka.configuration:
      brokers: kafka-test-kafka-bootstrap-kafka.apps.CHANGE_ME.com:443
      # brokers: kafka-test-kafka-bootstrap-kafka.apps.cluster-tracs-8e50.tracs-8e50.openshiftworkshop.com:443
      # brokers: kafka-test-kafka-bootstrap:9093
      security-protocol: SSL
      ssl-truststore-location: client.ts
      ssl-truststore-password: password
      ssl-truststore-type: PKCS12
      ssl-keystore-location: client.ks
      ssl-keystore-password: password
      ssl-keystore-type: PKCS12
      ssl-endpoint-algorithm: ""
# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache: DEBUG
    #org.apache.camel: DEBUG
    org.apache.camel.examples: DEBUG
