spec:
  template:
    spec:
      serviceAccountName: camel-kafka-tls-sa
      containers:
      - name: camel-kafka-tls
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/etc/config/
        - name: KAFKA_CLUSTER_CRT
          valueFrom:
            secretKeyRef:
              name: kafka-test-cluster-ca-cert
              key: ca.crt
        - name: KAFKA_USER_CRT
          valueFrom:
            secretKeyRef:
              name: my-user
              key: user.crt
        - name: KAFKA_USER_KEY
          valueFrom:
            secretKeyRef:
              name: my-user
              key: user.key
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "1.0"
        volumeMounts:
        - name: camel-kafka-tls-configmap-vol
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: camel-kafka-tls-configmap-vol
        configMap:
          name: camel-kafka-tls-configmap
            