apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-test
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    authorization:
      type: simple
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.2"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
